---
- name: Deploy GitHub Runner
  hosts: github-runner
  become: yes
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  tasks:
    - name: Deploy runner
      ansible.builtin.include_role:
        role: monolithprojects.github_actions_runner
      vars:
        runner_name: "{{ ansible_facts.node_name }}-{{ runner.key }}"
        runner_dir: "{{ base_runner_dir }}/{{ runner.key }}"
        runner_labels: "{{ runner.value.labels | default(default_runner_labels) }}"
        runner_state: "{{ runner.value.state | default('started') }}"
      with_dict:
        "{{ github_runners }}"
      loop_control:
        loop_var: runner